# Generated by Django 4.1.13 on 2024-10-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(db_index=True, max_length=64)),
                ('locations', models.CharField(db_index=True, max_length=120)),
                ('job_title', models.CharField(db_index=True, max_length=64)),
                ('job_description', models.CharField(db_index=True, max_length=120)),
                ('hourly_pay', models.CharField(max_length=10)),
                ('benefits', models.CharField(db_index=True, max_length=120)),
                ('review', models.CharField(db_index=True, max_length=120)),
                ('rating', models.IntegerField()),
                ('recommendation', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(db_index=True, max_length=500)),
                ('jobDescription', models.CharField(db_index=True, max_length=1000)),
                ('jobLocation', models.CharField(db_index=True, max_length=500)),
                ('jobPayRate', models.CharField(db_index=True, max_length=120)),
                ('maxHoursAllowed', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Vacancies',
            },
        ),
    ]
