name: Django Testing

on:
  push:
    branches: [ "test", "project-resources", "shazia_testing" ]
  pull_request:
    branches: [ "test", "project-resources", "shazia_testing" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mongo:latest
        ports:
          - 27017:27017
        options: --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install MongoDB Shell (mongosh)
        run: |
          curl -fsSL https://www.mongodb.org/static/pgp/server-6.0.asc | sudo gpg --dearmor -o /usr/share/keyrings/mongodb.gpg
          echo "deb [signed-by=/usr/share/keyrings/mongodb.gpg] https://deb.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-org-shell

  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r review_backend/requirements.txt
          pip install django

      - name: Wait for MongoDB to start
        run: |
          until mongosh --eval 'db.adminCommand("ping")'; do sleep 1; done

      - name: Run Tests
        env:
          MONGO_URI: "mongodb://db:27017"
        run: |
          python manage.py test