name: Jest Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust if needed

      - name: Install dependencies
        working-directory: ./review_frontend
        run: npm install

      # Run Jest tests in CI mode
      - name: Run Jest Tests
        working-directory: ./review_frontend
        env:
          CI: true
        run: npm test -- --coverage
