name: Pylint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.1'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pylint-django

      - name: Run Pylint
        run: |
          pylint --ignore=node_modules --disable=import-error .
