name: Tests

on: [push, pull_request]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.1"
    - name: Run tests
      run: |
        pip install --upgrade pip
        pip install pytest
    - name: Test with pytest
      run: |
       pip install pytest pytest-cov
       pytest